package com.mybatis.auto.auto;

import java.util.List;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_name
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_level
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private Integer menuLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_path
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private String menuPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_order
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private Integer menuOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_id
     *
     * @return the value of menu.menu_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_id
     *
     * @param menuId the value for menu.menu_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_name
     *
     * @return the value of menu.menu_name
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_name
     *
     * @param menuName the value for menu.menu_name
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_level
     *
     * @return the value of menu.menu_level
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public Integer getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_level
     *
     * @param menuLevel the value for menu.menu_level
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_id
     *
     * @return the value of menu.parent_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_id
     *
     * @param parentId the value for menu.parent_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_path
     *
     * @return the value of menu.menu_path
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_path
     *
     * @param menuPath the value for menu.menu_path
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_order
     *
     * @return the value of menu.menu_order
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    public boolean isChildFlag() {
        return childFlag;
    }

    public void setChildFlag(boolean childFlag) {
        this.childFlag = childFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_order
     *
     * @param menuOrder the value for menu.menu_order
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    boolean childFlag;
     int NodeId;

    public int getNodeId() {
        return NodeId;
    }

    public void setNodeId(int nodeId) {
        NodeId = nodeId;
    }

    public List getSubMenuList() {
        return SubMenuList;
    }

    public void setSubMenuList(List subMenuList) {
        SubMenuList = subMenuList;
    }

    List SubMenuList;


}