package com.dao.auto;

public class MenuRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.role_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.menu_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.id
     *
     * @return the value of menu_role.id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.id
     *
     * @param id the value for menu_role.id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.role_id
     *
     * @return the value of menu_role.role_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.role_id
     *
     * @param roleId the value for menu_role.role_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.menu_id
     *
     * @return the value of menu_role.menu_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.menu_id
     *
     * @param menuId the value for menu_role.menu_id
     *
     * @mbg.generated Fri Sep 28 11:07:04 GMT+08:00 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
}